# Generated by Django 5.2.6 on 2025-09-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_textoanalizado_nube_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='contenido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='frecuencia',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='textoanalizado',
            name='nube_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='nubes/'),
        ),
        migrations.AlterField(
            model_name='textoanalizado',
            name='tokens_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
