# Generated by Django 5.2.6 on 2025-09-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_alter_palabra_contenido_alter_palabra_frecuencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('frecuencia', models.PositiveIntegerField()),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigramas', to='analisis.textoanalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Trigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('frecuencia', models.PositiveIntegerField()),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigramas', to='analisis.textoanalizado')),
            ],
        ),
    ]
